pipeline {
    agent {
        docker {
            image 'maven:3-openjdk-8'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests -f hell-app/pom.xml clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -f hell-app/pom.xml test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './deliver-script.sh'
            }
        }
    }
}